version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
